using KRMApiResume.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace KRMApiResume.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController: Controller
    {

        List<BlogPost> Posts = new List<BlogPost>
        {
            new BlogPost
            {
                Id = 1,
                Title = "Example post",
                Summary = "This is an example post",
                Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                Author = new Author
                {
                    Id = 1,
                    Name = "Kristaps",
                    Description = "Hi, my name is Kristaps"
                },
                Tags = new string[]
                {
                    "example",
                    "post"
                }
            }
        };

        //Get api/values
        [HttpGet]

        // Get a list of blog post from database
        public ActionResult<IEnumerable<BlogPost>> Get()
        {
            return Posts;
        }
        //Get api/values/id
        [HttpGet("{id}")]
        public ActionResult<BlogPost> Get(int id)
        {
            throw new NotImplementedException();
        }
        //Post api/values
        [HttpPost]
        public void Post([FromBody] BlogPost value)
        {
            throw new NotImplementedException();
        }
        //Put api/values/5
        [HttpPut("{id}")]
        public void Put(int id, [FromBody] BlogPost value)
        {
            throw new NotImplementedException();
        }
        //Delete api/Values
        [HttpDelete("{id}")]
        public void Delete(int id)
        {
            throw new NotImplementedException();
        }

    }
}
