import { FC, useEffect, useState } from "react";
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Box from '@mui/material/Box';
import IconButton from '@mui/material/IconButton';
import Brightness4Icon from '@mui/icons-material/Brightness4';
import Brightness7Icon from '@mui/icons-material/Brightness7';
import { Button, css, MenuItem, Select, Typography } from "@mui/material";
import { useTheme } from "next-themes";
const inter = Inter({ subsets: ['latin'] })
// Add ThemeUpdater and PageTitle

export default function Home() {
  const { theme, resolvedTheme, setTheme } = useTheme();
  const [mounted, setMounted] = useState(false);
  // When mounted on client, now we can show the UI
  useEffect(() => setMounted(true), []);
    if (!mounted)
    return (
      <div
        // css={css`
        //   min-height: 162.38px;
        // `}
      ></div>
    );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <main className={styles.main}>
        <div className={styles.description}>
          <h1>Karl Angrand</h1>
          
          {/* Eventually we will want to move this to navbar */}
          <Box
        //   sx={{
        // display: 'flex',
        // width: '100%',
        // alignItems: 'center',
        // justifyContent: 'center',
        // bgcolor: 'background.default',
        // color: 'text.primary',
        // borderRadius: 1,
        // p: 3,
      //}}
          >
            Toggle {resolvedTheme === "light" ? "dark" : "light"} mode
          <IconButton sx={{ ml: 1 }} onClick={() => setTheme(resolvedTheme === "light" ? "dark" : "light")}>
           {resolvedTheme ==="light" ? <Brightness4Icon /> : <Brightness7Icon />}
          </IconButton>
          </Box>  {/**/}
        </div>
      </main>
      
    </>
  )
}
